name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}
        
    - name: Set permissions for private key
      run: |
        echo "${{ env.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@51.20.72.32 'sudo docker pull tukilla/pythonapp'
