name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Sleep for 30 seconds
      run: Start-Sleep -s 30
      shell: bash
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Set permissions for private key
      run: |
        echo "${{ secrets.DJOKICA }}" > key.pem
        chmod 600 key.pem
        
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.SERVER_IP }} 'sudo docker pull tukilla/pythonapp'

    - name: Stop Docker container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.SERVER_IP }} 'sudo docker stop myapp'
        
    - name: Run Docker container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.SERVER_IP }} 'sudo docker run -d --rm --name myapp -p 80:5000 tukilla/pythonapp'
